### ISSUE TITLE
[FEATURE] Reset map

### ISSUE THREAD

**Issue by BastienMarais** [Astropilot/ValheimTooler#1]
Hi @Astropilot,

After testing many of the features offered by ValheimTooler V1.0 I think I have found a new idea to implement😉.

Currently, the tool proposes to explore the whole map but it's impossible to go back and a miss click is so quickly arrived 😅... 

I think it would be complicated to restore the "legal" exploration but at least reset it to avoid a case of no return and not spoil a character on this world permanently.

Adding a "reset map exploration" button could be relevant what do you think ?

**Comment by Astropilot** [comment]
Hello Bastien,

I agree with you, the exploration feature of minimap being irreversible, it would be appropriate to propose to reset minimap so as not to spoil the gaming experience.
I will add it to the roadmap for the next version.

**Comment by Astropilot** [comment]
This feature is now available in version 1.1.0 of the cheat!
