### ISSUE TITLE
Mistlands update, Fails to generate config file.

### ISSUE THREAD

**Issue by xFusionLordx** [Astropilot/ValheimTooler#11]
Fails to generate config, in the mistlands update.
Version Tested: v1.6.0
Console Output: 

> [Info   : Unity Log] 12/17/2022 22:49:59: [ValheimTooler - ConfigManager] Failed to find config_vt.path file. Fallback to default configuration.

**Comment by Astropilot** [comment]
Hi @xFusionLordx , 
Could you tell me if you are using the standalone version (with the launcher) or the BepInEx version? If the latter, are you using a mod manager?

**Comment by xFusionLordx** [comment]
BepInEx Via ThunderStore

**Comment by GrimmLiberty** [comment]
looks like.... 
[ValheimTooler - ConfigManager] Failed to find config_vt.path file. Fallback to default configuration. 
is the culprit.

**Comment by Astropilot** [comment]
I confirmed the bug for modded version on my side, I will make a patch tonight

**Comment by Astropilot** [comment]
The configuration system has been corrected for the BepInEx version in the latest https://github.com/Astropilot/ValheimTooler/releases/tag/v1.7.0!
