### ISSUE TITLE
cursor issue : stuck always on

### ISSUE THREAD

**Issue by Maarken31** [Astropilot/ValheimTooler#12]
Hello,
since the last update (15 december 2022) my cursor is "stuck on" while the mode is on.
And there no bug when the mod is off, so i really think the mod is the reason why the cursor is stuck on, without inventory open, it's cause asynchronisation betewwen camera displacement and cursor displacement.

Like i'm not fluent in english i will add a description in french :
Le problème est que le curseur est tout le temps visible même quand l'inventaire n'est pas ouvert, ce qui cause une asynchronisation entre la caméra et le déplacement du curseur. ce qui d'une part est visuellement perturbant et d'autre part envoi le curseur à l’extérieur du jeu.

Thank you

**Comment by BastienMarais** [comment]
Salut !

Je viens de retester et de mon côté le curseur disparait bien lorsque je cache l'outil.

Quelques petites questions pour faciliter le taff du dev :
* L'outil  a été installé via le launcher Valheim Tooler ou par BepInEx ? (Un soucis a déjà été remonté sur la version mod)
* Le curseur est visible lorsque l'outil est ouvert mais lorsque tu le cache (touche SUPPR) le curseur ne disparait pas c'est bien ça ?

Bonne journée,
Bast

**Comment by Maarken31** [comment]
Salut,

j'utilise le thunderstore mod manager (d'overwolf) qui passe par BepInEx donc, mais en voulant faire un imprim ecran j'ai fait "alt+impr ecran" et ça a fait disparaitre mon problème ...
Du coup merci :p

Bonne journée

________________________________
De : Bastien Marais ***@***.***>
Envoyé : lundi 19 décembre 2022 17:34
À : Astropilot/ValheimTooler ***@***.***>
Cc : Maarken31 ***@***.***>; Author ***@***.***>
Objet : Re: [Astropilot/ValheimTooler] cursor issue : stuck always on (Issue #12)


Salut !

Je viens de retester et de mon côté le curseur disparait bien lorsque je cache l'outil.

Quelques petites questions pour faciliter le taff du dev :

  *   L'outil a été installé via le launcher Valheim Tooler ou par BepInEx ? (Un soucis a déjà été remonté sur la version mod)
  *   Le curseur est visible lorsque l'outil est ouvert mais lorsque tu le cache (touche SUPPR) le curseur ne disparait pas c'est bien ça ?

Bonne journée,
Bast

**Comment by BastienMarais** [comment]
Bon si ça remarche parfait 😁

Bonne journée

**Comment by Astropilot** [comment]
Bonjour @Maarken31,

Comme l'a précisé Bastien, lorsque la fenêtre du mod est affiché le curseur est affiché également, quand bien même tu n'a pas l'inventaire ou autre fenêtre du jeu ouverte. Effectivement quand tu es sur la caméra ça te permet de naviguer sur le mod mais du coup ça te fais bouger la caméra et ton curseur peut sortir de la fenêtre du jeu.
Lorsque tu cache le mod (touche SUPPR) le curseur est à nouveau caché et verrouillé sur la caméra.

Cette fonctionnalité permet d'éviter de devoir ouvrir l'inventaire ou autre menu juste pour avoir le curseur et interagir avec le mod,
Du moment que le mod n'est pas affiché tu devrais ne pas avoir de problème de curseur.

Ce qui serait considéré comme un bug c'est si en masquant le mod le curseur reste affiché, mais si ce n'est pas le cas c'est le comportement normal du mod, éventuellement je peux faire un paramètre configurable pour autoriser ou non l'affichage automatique du curseur.

Cordialement,
Astropilot
