### ISSUE TITLE
Couldn't find post_install.chk file error

### ISSUE THREAD

**Issue by WesleyPizetta** [Astropilot/ValheimTooler#13]
Today they released the new patch 0.212.9 and after this, I am not being able to open the tooler. Tried to reinstall and by reading the crash reports I realized that one of the files is not being created (post_install.chk)

It returns this error: System.IO.FileNotFoundException

note: I'm using the standard version, not the BepInExMod

**Comment by Astropilot** [comment]
Hi @WesleyPizetta , if the launcher is trying to open the `post_install.chk`, it means that it considers that it is still installed but without being true.

Nevertheless I propose you a solution allowing you to reinstall the tool cleanly when the starting is blocked:
- On Steam in the game settings perform a file integrity check of Valheim which will restore the original game files
- In the folder where you installed ValheimTooler delete the folder `Backups` and the file `post_install.chk` if it exists
- Go to the folder `C:\Users\[YOUR USER]\AppData\Local\ValheimToolerLauncher` (think to replace `[YOUR USER]` by your session user) and delete its content.
- Simply restart the launcher and click again on `Install`, it should work again.

**Comment by WesleyPizetta** [comment]
Oh, thanks!

**Comment by Astropilot** [comment]
Glad to hear it!

Enjoy the tool again :)
