### ISSUE TITLE
Updated the tooler with features using patching.

### ISSUE THREAD

**Issue by themaoci** [Astropilot/ValheimTooler#14]
here is a link for the forked version: https://github.com/themaoci/ValheimTooler

- allow teleporting with restricted items (as patch)
- autopin usefull staff on map (as patch)
- do not kill player on the edge of the map (as patch)
- godmode (unable to kill you) (as patch)
- infinity stamina (as patch)
- fast crafting (as patch)
- sprint speedhack (kinda useless cuz it needs more patches) (as patch)
- zero cap all the time (infinity weight limit) (as patch)
- detecting anticheat (some easy way from loaded assemblies)
- disable features that are detected (mostly player ones the rest do not trigger the anticheat) - if anticheat is present
- enable/disable esp boxes

some speedup for esp's not doing calculations 2+ times if not needed

**Comment by Astropilot** [comment]
Hello @themaoci ,

Thank you for your interest in the project!
I hesitated for a long time whether to use Harmony or not, but I'm convinced by the advantages you presented.
I will incorporate a good part of your modifications.
I won't incorporate the parts related to the anti-cheat evasion, this cheat being already dangerous enough as it is, I prefer to let the community server owners block this cheat to avoid regrettable abuses (anyway as it is, it will be detected by most anti-cheats which scan the assemblies too).

I'll add you to the credits and thanks again for your work! 👏

**Comment by Astropilot** [comment]
Hello themaoci,

I have incorporated most of your developments in the new https://github.com/Astropilot/ValheimTooler/releases/tag/v1.7.0!

Thanks again for your work, which even allowed me to correct the ESP of the deposits!
