### ISSUE TITLE
Thumnail item bug ?

### ISSUE THREAD

**Issue by Astropilot** [Astropilot/ValheimTooler#21]
### Discussed in https://github.com/Astropilot/ValheimTooler/discussions/20

<div type='discussions-op-text'>

<sup>Originally posted by **Robert-Elias159** December 30, 2022</sup>
![bug](https://user-images.githubusercontent.com/48679892/210031706-313f3f64-db95-482e-a156-64d38dd2c063.png)
Is there anyway to make the icon become smaller ? </div>

**Comment by Astropilot** [comment]
Hi @Robert-Elias159,

I need some more information, are you using the BepInEx or the vanilla version? If the former are you using other mods along with ValheimTooler?

**Comment by Robert-Elias159** [comment]
@Astropilot Sorry for the late reply, and ye i'm using the BeplnEx with some other mods

**Comment by Astropilot** [comment]
No problem! Ok so it seems to be a problem with other mods that are adding new objects with bigger textures than the original ones. For the next patch I will put a resize of each image to be sure to display them in the same size

**Comment by Robert-Elias159** [comment]
> No problem! Ok so it seems to be a problem with other mods that are adding new objects with bigger textures than the original ones. For the next patch I will put a resize of each image to be sure to display them in the same size

Thank you

**Comment by Astropilot** [comment]
Hi there, this bug should have been patched on the new release (1.8.0). If not please feel free to re-open this issue!
