### ISSUE TITLE
Not working, update needed because game updated

### ISSUE THREAD

**Issue by fengyuan213** [Astropilot/ValheimTooler#23]

**Comment by Astropilot** [comment]
Hello @fengyuan213 , I checked but I didn't see any new update of the game. The actual version is still 0.212.9 that is compatible with my tool. I checked on my side and the tool is working. Can you elaborate on the problem that you have on your side?

**Comment by fengyuan213** [comment]
Hello, are u using the steam version? the latest version on my end is 0.213.4

**Comment by fengyuan213** [comment]
It was showing "  can not cast object to type System.Objects[] "on game launch
