### ISSUE TITLE
gamepass

### ISSUE THREAD

**Issue by rogueyoshi96** [Astropilot/ValheimTooler#24]
can this be done on gamepass i tried everything and cant get it to work

**Comment by Astropilot** [comment]
Hello,
Sorry but I don't know gamepass, indeed my launcher was designed for the steam version only but not having gamepass I could not adapt it.

**Comment by BastienMarais** [comment]
![image](https://user-images.githubusercontent.com/25180074/227323855-752e65d0-8226-4b2a-b66a-245e4dda5549.png)

There is a way to select the tool's installation folder. 
Select the installation folder containing the Valheim.exe and it should work I think.
