### ISSUE TITLE
Failed to Inject

### ISSUE THREAD

**Issue by VantaSSB** [Astropilot/ValheimTooler#27]
Status: Failed to inject: mono_object_get_class() returned NULL

This is happening while using the launcher, not the BepinEx version, after I've verified integrity of Valheim files and installed then launched while in the main menu. 

Any ideas how I can fix this? Sorry if I just haven't read some directions here, just seems easier to post an issue since I can't find anything on it in the write-up. Thank you in advance.

**Comment by semendereye** [comment]
same problem here

**Comment by faulconern1** [comment]
Same problem here. I though I struck gold after adding /valheim.exe at the end of the directory field. However, upon clicking launch it crashes.

**Comment by Astropilot** [comment]
Hi, sorry for very long delay, do you guys use the steam version of the game? @VantaSSB @semendereye @faulconern1

**Comment by crossfire151** [comment]
I have the same issue. I am using the steam version of the game,

**Comment by crossfire151** [comment]
any updates on a fix?

**Comment by Astropilot** [comment]
Hi @crossfire151 , sadly on my side I am unable to replicate the issue :/

**Comment by crossfire151** [comment]
How do we go about getting it to work?

**Comment by Astropilot** [comment]
As crossfire151 seems to use Vortex Mod Manager, I would like to know if the other people who are having the same issue are using mods (if the case with which mod manager)?

**Comment by ltearth** [comment]
same issue here, failed to inject couldn't process valheim, disappointing

**Comment by Astropilot** [comment]
> same issue here, failed to inject couldn't process valheim, disappointing

Well instead of just saying it doesn't work maybe giving some more information could be help me understand why is it not working on your side? Which version of the game (steam or xbox) are you using? The classic or public test version? Which OS? Are you using a mod manager, if yes which one?

**Comment by Omniphantasm** [comment]
Failed to inject, crashes whether I launch on main menu or once I'm in game.

Steam version, no mods, completely clean install, new world, version 0.217.14 (n-12)

**Comment by Astropilot** [comment]
> Failed to inject, crashes whether I launch on main menu or once I'm in game.
> 
> Steam version, no mods, completely clean install, new world, version 0.217.14 (n-12)

Hi, thanks for the information.
Is it my launcher or the game that crash? If it is the former you should have a `crash_report.txt` file that have been generated in the same folder as the launcher. If you could share it so that I can know better what happened.

**Comment by PololoYT** [comment]
> > Failed to inject, crashes whether I launch on main menu or once I'm in game.
> > Steam version, no mods, completely clean install, new world, version 0.217.14 (n-12)
> 
> Hi, thanks for the information. Is it my launcher or the game that crash? If it is the former you should have a `crash_report.txt` file that have been generated in the same folder as the launcher. If you could share it so that I can know better what happened.

crash_report.txt is not created in the Valheim folder, but the mono_object_get_class() returned NULL error appears

**Comment by PololoYT** [comment]
> > Failed to inject, crashes whether I launch on main menu or once I'm in game.
> > Steam version, no mods, completely clean install, new world, version 0.217.14 (n-12)
> 
> Hi, thanks for the information. Is it my launcher or the game that crash? If it is the former you should have a `crash_report.txt` file that have been generated in the same folder as the launcher. If you could share it so that I can know better what happened.

The game crashes, the launcher itself gives an error mono_object_get_class() returned NULL, but the launcher itself does not crash, I can show it in Discord

**Comment by Astropilot** [comment]
Hi, I confirm that I am able to reproduce the issue with the latest version of the game (0.217.14). 

I deduce from this that others who had the problem previously were probably playing on the public test version, which was more advanced than the official release. Now that the latest official version has joined the public test, ValheimTooler is no longer sufficiently up to date, so I'm going to prepare an update.

**Comment by Astropilot** [comment]
> @Astropilot love this mod. Been using it for almost a year now and it has been super helpful! I wanted to post this error here in case it is of any use to you. I am using the manual BepInEx install of Tooler and, with the new game version 0.217.14, I am getting this error in the BepInEx console upon booting up the game. The game does not crash, but the Tooler never loads. Let me know if I can provide any more info!
> ![Valheim_Tooler_BepInEx_Error](https://github.com/Astropilot/ValheimTooler/assets/10199270/34572905-42e6-4fc8-ae08-61ba1ceb8264)
> 

Hi @dhurlburt ,
Thank you for reporting, as I was saying in my previous message, the new game version if not yet compatible with my tool, an update is coming that will fix the bug described in this issue and your's too.

**Comment by Astropilot** [comment]
The bug should have been fixed in the new release! https://github.com/Astropilot/ValheimTooler/releases/tag/v1.9.0
