### ISSUE TITLE
[feature-request] filter teleport Targets

### ISSUE THREAD

**Issue by meanliar** [Astropilot/ValheimTooler#30]
right now the teleport targets list can be excessively long. allowing filters (either by typed info, so we can use characters to distinguish location types #$+ etc, or icon so we can find only Homes/Fires/etc) would help make the feature more usable.

**Comment by Astropilot** [comment]
Feature added in the new release! https://github.com/Astropilot/ValheimTooler/releases/tag/v1.9.0
