### ISSUE TITLE
Add [Chinese] language->translations.cfg

### ISSUE THREAD

**Issue by qq2506665200** [Astropilot/ValheimTooler#35]
hi Astropilot,ValheimTooler is exceptionally great that I have seen, I use it regularly and I share it with my friends.
I've finished the translation of the Chinese version. I also send you the "translations.cfg".

![QQ截图20231219173845](https://github.com/Astropilot/ValheimTooler/assets/64523469/7b252b38-9ade-4ade-93ef-587305ca4416)

[translations.zip](https://github.com/Astropilot/ValheimTooler/files/13713799/translations.zip)

**Comment by Astropilot** [comment]
Hi @qq2506665200 , thanks! It will be incorporated into the next version.

Kind regards,
Astropilot

**Comment by qq2506665200** [comment]
> 将他放置到哪个文件夹

ValheimTooler可执行文件是没有读取translations.cfg的，你需要下载ValheimTooler源码并替换translations.cfg编译生成ValheimTooler.dll在注入游戏即可。

**Comment by BastienMarais** [comment]
You'll have to go through the injection process, which will be integrated into the next version (normally before the end of the year).

**Comment by imLahm21** [comment]
hh，有些困难，等作者更新

**Comment by Chaaoo** [comment]
哥们能发一下中文吗0.0

> hi Astropilot,ValheimTooler is exceptionally great that I have seen, I use it regularly and I share it with my friends. I've finished the translation of the Chinese version. I also send you the "translations.cfg".
> 
> ![QQ截图20231219173845](https://private-user-images.githubusercontent.com/64523469/291543614-7b252b38-9ade-4ade-93ef-587305ca4416.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4Nzk0MTYsIm5iZiI6MTcwNjg3OTExNiwicGF0aCI6Ii82NDUyMzQ2OS8yOTE1NDM2MTQtN2IyNTJiMzgtOWFkZS00YWRlLTkzZWYtNTg3MzA1Y2E0NDE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDEzMDUxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczY2U1MDIzNTVmYzM4Zjc3MTZiZjkzZWMyNzE4MWEyYWIyNmY1MjhkNWUxZjQwNjk4MzY3MmRmNDMzYzE3NTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Eypl0PXc2c2-9Vy-KTx0Gy-xfbqI-qd4KEOTWK_VZKo)
> 
> [translations.zip](https://github.com/Astropilot/ValheimTooler/files/13713799/translations.zip)

**Comment by Astropilot** [comment]
The chinese translation have been added to the [new version (1.10.0)](https://github.com/Astropilot/ValheimTooler/releases/tag/v1.10.0)!
