### ISSUE TITLE
failed to inject:mono_object_get_class() returned NULL

### ISSUE THREAD

**Issue by Goggr5** [Astropilot/ValheimTooler#37]
When I try to launch it the game crashes and an error message says "failed to inject:mono_object_get_class() returned NULL"

**Comment by Astropilot** [comment]
Hi, I will need some more information to understand why does this happens,

- On which version of the game are you?
- Is it the game from Steam or from the xbox game pass?
- Which version of ValheimTooler do you use?
- Do you use mods?

Kind regards,
Astropilot

**Comment by WilczaQ** [comment]
I have the same problem. The latest game version (0.217.38). ValheimTooler 1.9.2. I have a graphics mod and another mod for unrestricted portals. Steam version. BepInEx mod not working too.

**Comment by Astropilot** [comment]
> I have the same problem. The latest game version (0.217.38). ValheimTooler 1.9.2. I have a graphics mod and another mod for unrestricted portals. Steam version. BepInEx mod not working too.

Hi @WilczaQ ,
The standalone version (with the launcher) cannot work when you are using mods, the mod version should be used instead.
Which mod manager do you use?

**Comment by WilczaQ** [comment]
@Astropilot r2modman.

**Comment by WilczaQ** [comment]
@Astropilot now it's working, BepInEx not loading correctly before. I simply reinstalled the game

**Comment by Astropilot** [comment]
Hi, I'm closing this issue as I haven't had a reply from the original author. Feel free to open it again if needed.
