### ISSUE TITLE
[FEATURE] Automatic recording of important positions on the map

### ISSUE THREAD

**Issue by BastienMarais** [Astropilot/ValheimTooler#4]
Hi! 

I have a new idea that might be fun!

An option to automatically save on the map (with dots) the interesting positions for the player. 
For example, I pass near a copper ore and automatically it adds a marker on the map with "copper". 
We can also imagine the same principle with the marking of dungeons.

Do you think this is feasible in your roadmap?

**Comment by themaoci** [comment]
https://www.nexusmods.com/valheim/mods/1444 -> have fun

**Comment by Astropilot** [comment]
After more than a year and a half of waiting the feature is finally available in the new version (v1.7.0) thanks to themaoci, see the changelog of the release: https://github.com/Astropilot/ValheimTooler/releases/tag/v1.7.0 😄
