### ISSUE TITLE
Heart and Home Update

### ISSUE THREAD

**Issue by m-maranan** [Astropilot/ValheimTooler#6]
Hi! Are you updating this for Heart and Home? Its definitely a useful tool in creative gameplay but the list of items that can be spawned were not updated. Thank you!

**Comment by Astropilot** [comment]
Hi @m-maranan , I will look at it this Sunday! :)

**Comment by m-maranan** [comment]
Thanks Man!

**Comment by Astropilot** [comment]
Hi @m-maranan , I'm really sorry for the delay! I just updated the tool, the list of items that can be spawned is now automatically updated with each patch of the game!

**Comment by m-maranan** [comment]
No worries man!
