### ISSUE TITLE
Mistlands Update..

### ISSUE THREAD

**Issue by m-maranan** [Astropilot/ValheimTooler#9]
Hi,

I know this is too much to ask haha! But are you going to update this for the mistlands patch?

Thanks!

**Comment by Astropilot** [comment]
Hello @m-maranan , an update is planned for today or tomorrow!

**Comment by sm0keyyy** [comment]
> Hello @m-maranan , an update is planned for today or tomorrow!

You're too awesome my friend!

**Comment by Astropilot** [comment]
Hi, I updated the tool, it should work now with the latest version of the game (0.212.7 Mistlands). Simply start the launcher and the update should appear on top :)

See [the release](https://github.com/Astropilot/ValheimTooler/releases/tag/v1.6.0) for the complete changelog.
